import type { ModelOption } from "./model-picker";
export type { ModelOption } from "./model-picker";

export type Criticality = "routine" | "important" | "critical";
export type ReviewAction = "confirm" | "unknown" | "reject";
export type FindingJudgment = "worth_reviewing" | "not_material" | "needs_context" | "false_positive";
export type WorkflowStep = 1 | 2 | 3 | 4;
export type WorkspaceView = "workspace" | "library" | "usage" | "settings";

export type Premise = { candidate_id: string; kind: string; statement: string; quality_state: string; attention_reason?: string; anchor?: { exact_excerpt: string } };
export type Extraction = { id: string; status: string; provider: string; model: string; result: { title: string; decision_question: string; context: string; chosen_option?: string; rationale: string; suggested_criticality: Criticality; criticality_reason: string; premises: Premise[] } };
export type Decision = { id: string; title: string; question: string; context: string; chosen_option?: string; rationale: string; criticality: Criticality; preservation_policy: string; status: string; created_at: string; premises: Array<{ id: string; kind: string; statement: string; anchor?: { exact_excerpt: string } }>; challenge?: DecisionChallenge | null };
export type DecisionListItem = { id: string; title: string; question: string; chosen_option?: string; criticality: Criticality; status: string; premise_count: number; revisit_count: number; pending_revisit_count: number; last_revisited_at?: string; created_at: string };
export type DecisionLibrary = { items: DecisionListItem[]; total: number };
export type PersonalWorkspace = { id: string; name: string; account_id: string; account_name: string; mode: "local_personal" | "authenticated_personal"; created_at: string };
export type WorkspaceBootstrap = { models: ModelCatalog; workspace: PersonalWorkspace; library: DecisionLibrary };
export type Finding = { premise_id: string; premise_statement: string; relationship: string; confidence_band: string; explanation: string; missing_context_question?: string; new_excerpt: string; old_excerpt?: string; source_fallback_performed: boolean; finding_type?: "premise_change" | "new_constraint"; detection_source?: "model" | "deterministic_rules" | "deterministic_safety_net"; human_judgment?: FindingJudgment; human_notes?: string; judged_at?: string };
export type PremiseReview = { action: ReviewAction; statement: string; kind: string };
export type DecisionDraft = { title: string; question: string; context: string; chosenOption: string; rationale: string };
export type ModelCatalog = { default_model_id: string; models: ModelOption[] };
export type ChallengePoint = { premise_id: string; premise_statement: string; source_excerpt?: string; prompt: string; explanation: string };
export type DecisionChallenge = { status: "draft" | "confirmed"; weakest_assumption: ChallengePoint; missing_evidence: ChallengePoint; strongest_counterargument: ChallengePoint; reversal_condition: ChallengePoint; provider: string; model: string; prompt_version: string; latency_ms?: number; input_tokens?: number; output_tokens?: number; estimated_cost_usd?: number; generated_at: string; confirmed_at?: string; reviewer_notes?: string };
export type Job = { id: string; kind: "extraction" | "revisit" | "challenge"; status: "queued" | "running" | "succeeded" | "failed" | "cancelled"; phase: string; progress: number; result?: unknown; error?: string };
export type RevisitResult = { id: string; decision_id: string; status: string; findings: Finding[]; provider?: string; model?: string; prompt_version?: string; latency_ms?: number; input_tokens?: number; output_tokens?: number; estimated_cost_usd?: number; evidence_filename?: string; created_at: string };
export type ComparisonRun = { modelId: string; label: string; result: RevisitResult };
export type Share = { id: string; decision_id: string; token: string; status: string; url: string | null; created_at: string; expires_at: string | null; revoked_at: string | null };
export type AuditEvent = { id: string; kind: "decision" | "challenge" | "evidence" | "judgment"; title: string; detail: string; timestamp: string };
export type UsageRun = { id: string; kind: "extraction" | "revisit" | "challenge"; provider: string; model: string; prompt_version: string; location: "local" | "hosted" | "unknown"; latency_ms?: number; input_tokens?: number; output_tokens?: number; estimated_cost_usd?: number; created_at: string; decision_id?: string };
export type UsageModel = { provider: string; model: string; location: "local" | "hosted" | "unknown"; run_count: number; total_tokens: number; known_cost_usd: number; unpriced_run_count: number; average_latency_ms?: number };
export type UsageSummary = { total_runs: number; extraction_runs: number; revisit_runs: number; challenge_runs: number; local_runs: number; hosted_runs: number; unknown_location_runs: number; total_tokens: number; tokenized_run_count: number; known_cost_usd: number; unpriced_run_count: number; models: UsageModel[]; recent_runs: UsageRun[] };
export type PilotMetrics = { decision_count: number; revisit_count: number; judgment_count: number; share_count: number; export_count: number; challenge_confirmation_count: number; active_days: number; repeat_use_observed: boolean; latest_activity_at?: string };
export type PersistedWorkspaceSession = { workspaceId?: string; source?: string; evidence?: string; sourceMode?: "paste" | "file"; view?: WorkspaceView; workflowView?: WorkflowStep; selectedModelId?: string; comparisonModelId?: string; compareMode?: boolean; decisionId?: string; extraction?: Extraction; draft?: DecisionDraft; reviews?: Record<string, PremiseReview>; criticality?: Criticality; selectedPremise?: string };
export type EvidenceDraft = { workspaceId: string; content: string; selectedModelId: string; comparisonModelId: string; compareMode: boolean; updatedAt: string };
