import type { components } from "@/lib/api-contract";

type ApiSchema = components["schemas"];

export type Criticality = ApiSchema["Criticality"];
export type ReviewAction = "confirm" | "unknown" | "reject";
export type FindingJudgment = "worth_reviewing" | "not_material" | "needs_context" | "false_positive";
export type WorkflowStep = 1 | 2 | 3 | 4;
export type WorkspaceView = "workspace" | "library" | "usage" | "settings";

export type ModelOption = ApiSchema["ModelOption"];
export type Premise = ApiSchema["CandidatePremise"];
export type Extraction = ApiSchema["ExtractionRead"];
export type Decision = ApiSchema["DecisionRead"];
export type DecisionListItem = ApiSchema["DecisionListItem"];
export type DecisionLibrary = ApiSchema["DecisionListRead"];
export type PersonalWorkspace = ApiSchema["WorkspaceRead"];
export type WorkspaceBootstrap = ApiSchema["WorkspaceBootstrapRead"];
export type Account = ApiSchema["AccountRead"];
export type SessionSummary = ApiSchema["SessionSummaryRead"];
export type Secret = ApiSchema["SecretRead"];
export type AccountSettings = ApiSchema["AccountSettingsRead"];
export type Finding = ApiSchema["RevisitFinding"];
export type PremiseReview = { action: ReviewAction; statement: string; kind: string };
export type DecisionDraft = { title: string; question: string; context: string; chosenOption: string; rationale: string };
export type ModelCatalog = ApiSchema["ModelCatalogRead"];
export type ChallengePoint = ApiSchema["ChallengePoint"];
export type DecisionChallenge = ApiSchema["DecisionChallengeRead"];
export type Job = ApiSchema["JobRead"];
export type RevisitResult = ApiSchema["RevisitRead"];
export type ComparisonRun = { modelId: string; label: string; result: RevisitResult };
export type Share = ApiSchema["ShareRead"];
export type AuditEvent = { id: string; kind: "decision" | "challenge" | "evidence" | "judgment"; title: string; detail: string; timestamp: string };
export type UsageRun = ApiSchema["UsageRunRead"];
export type UsageModel = ApiSchema["UsageModelRead"];
export type UsageSummary = ApiSchema["UsageSummaryRead"];
export type PilotMetrics = ApiSchema["PilotMetricsRead"];
export type UsageDashboard = ApiSchema["UsageDashboardRead"];
export type DecisionWorkspace = ApiSchema["DecisionWorkspaceRead"];
export type PersistedWorkspaceSession = { workspaceId?: string; source?: string; evidence?: string; sourceMode?: "paste" | "file"; view?: WorkspaceView; workflowView?: WorkflowStep; selectedModelId?: string; comparisonModelId?: string; compareMode?: boolean; decisionId?: string; extraction?: Extraction; draft?: DecisionDraft; reviews?: Record<string, PremiseReview>; criticality?: Criticality; selectedPremise?: string };
export type EvidenceDraft = { workspaceId: string; content: string; selectedModelId: string; comparisonModelId: string; compareMode: boolean; updatedAt: string };
